# -*- coding: utf-8 -*-
# vim: ft=yaml
---
docker:
  process_signature: '/usr/bin/docker'
  install_docker_py: true
  python_package: docker
  refresh_repo: true
  configfile: /etc/default/docker
  config: []
  daemon_config: {}
  version: ''
  rootuser: root

  use_upstream_repo: true
  use_old_repo: false
  proxy: false

  pkgs:
    - iptables
    - ca-certificates

  pkg:
    name: docker-ce
    old_name: docker-engine
    # For backward compatibility, this will be overriden by docker:version, if defined
    version: latest
    allow_updates: false
    hold: false
    use_upstream_app: false  # macos

  pip:
    install_pypi_pip: false
    upgrade: false

  compose_version: ''

  containers:
    skip_translate: None
    force_present: false
    force_running: false

  kernel:
    pkg:
      fromrepo: ''
    pkgs: []
