FROM elixir:1.10.0-alpine AS build

# install build dependencies
RUN apk add --no-cache build-base git npm python

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# set build ENV
ENV MIX_ENV=prod
ARG secret_key_base=5Irhh1BBJyTQBThFQABQxdsCjds3W3+FyUvJ1P8rxuibEmgsPpc4/yX9lk35SloH
ENV SECRET_KEY_BASE=$secret_key_base

# # install mix dependencies
COPY mix.exs .
COPY mix.lock .
COPY apps/seascape/mix.exs apps/seascape/
COPY apps/seascape_web/mix.exs apps/seascape_web/
COPY apps/seascape_ingest/mix.exs apps/seascape_ingest/
COPY config config
RUN mix do deps.get, deps.compile

# build assets
COPY apps/seascape_web/assets/package.json apps/seascape_web/assets/package-lock.json ./apps/seascape_web/assets/
COPY apps/seascape_web/assets/node_modules/ ./apps/seascape_web/assets/node_modules/

# Fix symlink problems:
COPY deps/phoenix ./apps/seascape_web/assets/node_modules/phoenix/
COPY deps/phoenix_live_view ./apps/seascape_web/assets/node_modules/phoenix_live_view/
COPY deps/phoenix_html ./apps/seascape_web/assets/node_modules/phoenix_html/
COPY deps/phoenix_live_dashboard ./apps/seascape_web/assets/node_modules/phoenix_live_dashboard/
RUN tree apps/seascape_web/assets

# Continue with building front-end deps
RUN npm --prefix ./apps/seascape_web/assets ci --progress=false --no-audit --loglevel=error

COPY apps/seascape_web/priv apps/seascape_web/priv
COPY ./apps/seascape_web/assets ./apps/seascape_web/assets
RUN npm run --prefix ./apps/seascape_web/assets deploy
RUN mix phx.digest
COPY ./apps/seascape_web/priv/static ./apps/seascape_web/priv/static

# compile and build release
COPY ./apps/seascape/lib/ ./apps/seascape/lib/
COPY ./apps/seascape_web/lib/ ./apps/seascape_web/lib/
# COPY ./apps/seascape_ingest/lib/ ./apps/seascape_ingest/lib/
# uncomment COPY if rel/ exists
# COPY rel rel
RUN mix do compile, release web

# prepare release image
FROM alpine:3.9 AS app
RUN apk add --no-cache openssl ncurses-libs

WORKDIR /app

RUN chown nobody:nobody /app

USER nobody:nobody

COPY --from=build --chown=nobody:nobody /app/_build/prod/rel/web ./

ENV HOME=/app

CMD ["bin/web", "start"]