#cloud-config

users:
    - default

ssh_pwauth: True

write_files:
    - encoding: b64
      content: ${deploy_key}
      owner: root:root
      path: /root/.ssh/id_rsa
      permissions: '600'
    - encoding: b64
      content: ${deploy_pubkey}
      owner: root:root
      path: /root/.ssh/id_rsa.pub
      permissions: '600'

runcmd:
    - "echo \"Starting runcmd as $(whoami)\""
    - "printf 'LANG=en_US.UTF-8' > /etc/locale.conf"
    - "localectl set-locale LANG=en_US.UTF-8"
    - "printf \"\n127.0.0.1\tsalt\n\" >> /etc/hosts"
    - "printf \"\n\" >> /root/.ssh/id_rsa"
    - "yum install -y https://repo.saltstack.com/py3/redhat/salt-py3-repo-latest.el8.noarch.rpm"
    - "yum clean expire-cache"
    - "yum install -y salt-master salt-minion salt-ssh salt-syndic salt-cloud salt-api"
    - "systemctl start salt-master"
    - "sleep 10"
    - "systemctl start salt-minion"
    - "sleep 10"
    - "salt-key -yA"
    - "touch /etc/cloud_init_finished"

package_upgrade: True

hostname: salt.seascape.example

final_message: "The system is up, after $UPTIME seconds"
