use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :seascape_web, SeascapeWeb.Endpoint,
  url: [host: "seascape.example", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

config :seascape_ingest, SeascapeIngest.Endpoint,
  url: [host: "ingest.seascape.example", port: 80], # TODO is this setting important for an API-only app?
  check_origin: false

# Do not print debug messages in production
# config :logger, level: :info
config :logger, backends: [:console, RingLogger]
